### ISSUE TITLE
Make URL configurable

### ISSUE THREAD

**Issue by ndarilek** [jcsteh/nvda-llamaCpp#1]
Thanks for this, it looks like a V2 of something I wanted to prototype at work for trying to read our various metrics graphs and dashboards.

I wanted to host the server on one of our GPU hosts for better models and faster results. Would it be difficult adding a settings screen and making the URL configurable so those of us wanting to host a server elsewhere can do so?

If this is a desired feature, I can probably just hack the code locally to insert my own URL for testing, then PR a settings screen sometime in the next few weeks. I just don't know how to do it now and don't immediately have time to learn.

Thanks again.

**Comment by jcsteh** [comment]
I'd be happy to see this implemented, but I hate writing GUI, so I can't promise I'll get to it any time soon. I'll happily take a PR though. :)

As a temporary measure, I could at least allow the URL to be taken from a config key, which we'll need for the GUI setting anyway. That way, you could set it via the Python console once (or even edit nvda.ini) and it would stay that way.

**Comment by ndarilek** [comment]
I hate GUI work too, so I'm happy for this to be configurable, as long as there are instructions on how to do it. Thanks!

**Comment by beqabeqa473** [comment]
Submitted #2
